version: "3.8"
services:
  main:
    container_name: ${CONTAIN_NAME}
    image: ${IMAGE_NAME}
    volumes:
    - "/home/vagrant/${BRANCH}/logs:/tmp/petclinic-project/logs"
    ports:
    - "${PORT}:8080"
  uat:
    container_name: ${CONTAIN_NAME}
    image: ${IMAGE_NAME}
    volumes:
    - "/home/vagrant/${BRANCH}/logs:/tmp/petclinic-project/logs"
    ports:
    - "${PORT}:8080"
  dev:
    container_name: ${CONTAIN_NAME}
    image: ${IMAGE_NAME}
    volumes:
    - "/home/vagrant/${BRANCH}/logs:/tmp/petclinic-project/logs"
    ports:
    - "${PORT}:8080"